### ISSUE TITLE
Single-instance config not working

### ISSUE THREAD

**Issue by jistr** [saz/puppet-memcached#61] opened 2015-05-25 12:35 UTC
Hello :)

after merging of #54 , Puppet run in the TripleO [1] (an OpenStack installer) fails [2] with this message:

```
Error: Could not start Service[memcached_11211]: Execution of '/sbin/service memcached_11211 start' returned 6: Starting memcached_11211 (via systemctl):  Failed to start memcached_11211.service: Unit memcached_11211.service failed to load: No such file or directory.
```

We only include the class via `include ::memcached` [3] and set the `listen_ip` parameter via hiera:

```
[root@ov-xxpg5ugstxz-0-pka54d6w3ryz-controller-ssjphxhoikxj hieradata]# pwd
/etc/puppet/hieradata
[root@ov-xxpg5ugstxz-0-pka54d6w3ryz-controller-ssjphxhoikxj hieradata]# grep -ri memcached
controller.yaml:memcached::listen_ip: 192.0.2.19
```

I think by default puppet should use the service init file which is shipped in distro's packages, instead of writing it's own. We're probably not the only ones broken by this and probably also not the only ones who consider writing custom service init files an anti pattern unless there's no other choice. Should the default behavior be restored to a state which is more resembling of how it was before merging #54 ?

[1] https://wiki.openstack.org/wiki/TripleO
[2] https://bugs.launchpad.net/tripleo/+bug/1458520
[3] https://github.com/openstack/tripleo-heat-templates/blob/631b1afee180317e4eca5980e82238265f1a7049/puppet/manifests/overcloud_controller_pacemaker.pp#L358

**Comment by jistr** [comment] 2015-05-25 12:36
^ s/service configuration file/service init file/ ;)

**Comment by saz** [comment] 2015-05-25 18:18
On which distribution is this error happening?

**Comment by saz** [comment] 2015-05-25 19:14
I've reverted #54 for now, but I'd really like to get this feature in, but in a working state.

I don't see a problem in changing the init script. Especially if the distributions init script doesn't provide a feature which is used by many. Running multiple instances of memcached on the same host is a good example for this.

**Comment by jistr** [comment] 2015-05-25 19:26
Thanks :) The distro is Fedora 20, but i expect a newer Fedora or CentOS would have the same issue.

Yeah i see the point in case one needs to run multiple instances, but still believe the default single instance should use "standard" init scripts shipped with distros. This might be subjective though :)

**Comment by saz** [comment] 2015-05-26 09:12
This is really hard to achieve in a clean way, as it is possible to use ```memcached::instance``` directly to create new instances, which won't be working as expected.

The issue you're seeing seems to come from systemd. I don't know, how fedora is handling old sysvinit scripts with systemd.

I'm open for suggestions here, to get this working.

**Comment by jistr** [comment] 2015-05-26 10:30
What about allowing to override `$service_name` on `memcached::instance` via a parameter on the resource, and in `memcached` class passing `service_name => $::memcached::params::service_name` to the default `memcached::instance`?

**Comment by dansajner** [comment] 2015-05-26 16:40
@jistr I am working on a fix, but surprised that Fedora 20 isn't compatible with sysv init scripts.  systemd is documented as compatible with sysv init scripts and I've confirmed that it works on RHEL7. (although the init script provided has an issue with this memcached package thus re-enforcing your point about messing with init scripts!  I will post a fix for that too.)  

Adding this feature definitely makes the module more complex and potentially undesirable for simple memcached use cases due to custom init scripts that may change across OS versions.    

One fix I'm working up requires enumerating `$::operatingsystem` versions and then checking `$::operatingsystemmajrelease` within to identify sysv-init versus systemd.  This makes for some ugly puppet code, but I am not sure how else to approach this problem.

**Comment by jistr** [comment] 2015-05-27 08:08
@dansajner Thanks for looking into this. Regarding approach to the problem, is there a reason why the approach i tried to outline above wouldn't be suitable? Let me explain more clearly with code snippets.

```puppet
define memcached::instance(
  $service_name = undef,
) {
  # * when $service_name is undef, do what PR #54 did
  # * when $service_name is defined, use that for the service init file
}
```

```puppet
class memcached(
) {
  if $default_instance {
    memcached::instance {
      service_name => $::memcached::params::service_name,
    }
  }
}
```

**Comment by derekhiggins** [comment] 2015-05-27 08:58
Just a quick correction, the distro where this was running was Fedora 21 (not F20), the memcached version that was installed was
memcached-1.4.17-3.fc21.x86_64

**Comment by saz** [comment] 2016-01-30 13:21
As the work on multi-instance support seems to be staled, I'll close this issue

**Closed by saz** 2016-01-30 13:21 UTC
